#!/usr/bin/env php
<?php

/**
 * Helper script for getting _ss_environment.php defined constants into a unix environment
 */

if (count($argv) < 2) {
	die("No _ss_environment.php file specified");
}

$file = $argv[1];

include $file;

// known variables
$variables = array(
	"TEMP_FOLDER",
	"SS_DATABASE_CLASS",
	"SS_DATABASE_SERVER",
	"SS_DATABASE_USERNAME",
	"SS_DATABASE_PASSWORD",
	"SS_DATABASE_PORT",
	"SS_DATABASE_SUFFIX",
	"SS_DATABASE_PREFIX",
	"SS_DATABASE_TIMEZONE",
	"SS_DATABASE_NAME",
	"SS_DATABASE_CHOOSE_NAME",
	"SS_DEPRECATION_ENABLED",
	"SS_ENVIRONMENT_TYPE",
	"SS_DEFAULT_ADMIN_USERNAME",
	"SS_DEFAULT_ADMIN_PASSWORD",
	"SS_USE_BASIC_AUTH",
	"SS_SEND_ALL_EMAILS_TO",
	"SS_SEND_ALL_EMAILS_FROM",
	"SS_ERROR_LOG",
	"SS_GEM_PATH"
);

foreach($variables as $var) {
	if (defined($var)) {
		$val = constant($var);
		echo "export ${var}=${val}\n";
	}
}

$script = basename(__FILE__);
echo "\n# Run the following command to create environment variables: \n# eval $(php ${script} ${file})";